replicaCount: 1
image:
  repository: "[Container_registry_image]"
  tag: v1.8.0
  pullPolicy: IfNotPresent
# Container & Service port
ports:
  - name: http
    containerPort: 3000
    protocol: TCP

service:
  type: LoadBalancer
  ports: 
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: internal-app

# status:
#   loadBalancer: {}

# # Ingress controller info & domain that we will use for the app
# ingress:
#   enabled: false
#   className: ""
#   annotations: 
#     appgw.ingress.kubernetes.io/use-private-ip: 'true'
#     kubernetes.io/ingress.class: azure/application-gateway
#   hosts:
#     - host: svapi-dev.lumificyber.com
#       paths:
#         - path: /
#           pathType: Prefix
#           port: 80

#   tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# APP Variables need it for the deployment
# azurevar: 
# - name: "Secret"
#   value: "test"


# # Port to check if the application is ready
# readinessProbe:
#     httpGet:
#       path: /health
#       port: 5002
#     initialDelaySeconds: 60
#     periodSeconds: 50
# # Port to check if the app is already live
# livenessProbe:
#     httpGet:
#       path: /health
#       port: 5002
#     initialDelaySeconds: 60
#     periodSeconds: 50