apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workshop2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "workshop2.name" . }}
    helm.sh/chart: {{ include "workshop2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "workshop2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "workshop2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # env:
          #     {{- range .Values.azurevar }}
          #     - name: {{ .name }}
          #       value: {{ .value }}
          #     {{- end }} 
          ports:
           {{- toYaml .Values.ports | nindent 12 }}